PACKAGE_NAME="rtc-pcf85063-wittypi4"
PACKAGE_VERSION="1.0"
CLEAN="make clean"
MAKE="KDIR=/lib/modules/$kernelver/build MDIR=/lib/modules/$kernelver make"
BUILT_MODULE_NAME[0]="rtc-pcf85063-wittypi4"
DEST_MODULE_LOCATION[0]="/kernel/drivers/rtc"
AUTOINSTALL="yes"
