[project]
name = "wittypi4"
version = "0.2"
dependencies = [
    "i2cdevice >=1.0.0",
    "smbus2 >=0.4.2",
    "gpiozero >=2.0",
    "astral >=3.2",
    "pytimeparse >=1.1.8",
    "pyyaml >=6.0.1",
    "scheduleparse @ git+https://github.com/trackIT-Systems/scheduleparse.git@2026.10.1",
]
requires-python = ">=3.11"

[tool.setuptools]
packages = ["wittypi4"]

[project.scripts]
wittypid = "wittypi4.wittypid:main"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-cov",
]
